[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[functions]]
  directory = "src"
  node_bundler = "esbuild"

[functions."*"]
  external_node_modules = ["sqlite3"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/public/:splat"
  status = 200
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200
